channels:
- conda-forge
dependencies:
- catch2
- cmake
- cpppath
- doxygen
- fmt
- goosefem
- h5py
- highfive
- mathjax
- ninja
- numpy
- prrng
- pybind11
- python
- python-qpot >=0.10.1
- qpot >=0.11.0
- scikit-build
- setuptools_scm
- xtensor >=0.24.1
- xtensor-python
