channels:
  - conda-forge
dependencies:
  # dependencies
  - xtensor
  - goosefem
  - qpot

  # build tools
  - cmake
  - ninja
  - setuptools_scm

  # Python API
  - python
  - pyxtensor

  # run tests
  - catch2
  - prrng
  - numpy
  - python-qpot

  # run examples
  - fmt
  - highfive

  # build docs
  - doxygen
  - mathjax
