channels:
  - conda-forge
dependencies:
  # dependencies
  - xtensor
  - goosefem
  - qpot

  # optional dependencies
  - xsimd

  # build tools
  - cmake
  - setuptools_scm

  # Python API
  - python
  - pyxtensor

  # run tests
  - catch2
  - numpy

  # run examples
  - fmt
  - highfive

  # build docs
  - doxygen
  - mathjax
