channels:
- conda-forge
dependencies:
- catch2
- cmake
- doxygen
- fmt
- goosefem
- highfive
- mathjax
- ninja
- numpy
- prrng
- pybind11
- python
- python-qpot
- qpot >=0.10.0
- scikit-build
- setuptools_scm
- xtensor
- xtensor-python
