channels:
- conda-forge
dependencies:
- cmake
- doxygen
- gmattensor >0.10.1
- goosefem
- ninja
- numpy
- prrng >=1.6.1
- pybind11
- python
- python-prrng >=1.6.1
- python-qpot >=0.12.1
- qpot >=0.12.1
- scikit-build
- setuptools_scm
- xtensor >=0.24.2
- xtensor-python
