channels:
- conda-forge
dependencies:
- cmake
- doxygen
- goosefem
- ninja
- numpy
- pybind11
- python
- python-qpot >=0.12.1
- python-prrng
- qpot >=0.12.1
- scikit-build
- setuptools_scm
- xtensor >=0.24.2
- xtensor-python
