channels:
- conda-forge
dependencies:
- cmake
- doxygen
- gmattensor >0.10.1
- goosefem
- ninja
- numpy
- prrng >1.7.0
- pybind11
- python
- python-prrng >1.7.0
- scikit-build
- setuptools_scm
- xtensor >=0.24.2
- xtensor-python
