channels:
- conda-forge
dependencies:
- clang-format >=15.0.7
- cmake
- doxygen >=1.9.6
- gmattensor >0.10.1
- goosefem
- h5py
- ninja
- numpy
- pre-commit
- prrng >=1.11.1
- pybind11
- python
- python-prrng >=1.10.1
- scikit-build
- setuptools_scm
- tqdm
- xsimd
- xtensor >=0.24.6
- xtensor-python
