channels:
- conda-forge
dependencies:
- catch2
- cmake
- doxygen
- goosefem
- ninja
- numpy
- prrng
- pybind11
- python
- python-qpot >=0.10.1
- python-prrng
- qpot >=0.11.0
- scikit-build
- setuptools_scm
- xtensor >=0.24.1
- xtensor-python
