name: historic

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:

  standard:

    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-latest]

    defaults:
      run:
        shell: bash -e -l {0}

    name: ${{ matrix.runs-on }} • x64 ${{ matrix.args }}
    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v3

    - name: Create conda environment
      uses: mamba-org/setup-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv
        init-shell: bash
        cache-environment: true
        post-cleanup: all

    - name: Export version of this library
      run: |
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "SETUPTOOLS_SCM_PRETEND_VERSION=$LATEST_TAG" >> $GITHUB_ENV

    - name: Build and install Python module
      run: SKBUILD_CONFIGURE_OPTIONS="-DUSE_DEBUG=1" python -m pip install . -v --no-build-isolation

    - name: Run examples
      working-directory: examples
      run: |
        python Line1d_Cuspy_Laplace.py
        python Line1d_Cuspy_Laplace_LongRange.py
        python Line1d_Cuspy_Laplace_Nopassing.py
        python Line1d_Cuspy_Quartic.py
        python Line1d_SemiSmooth_Laplace.py
        python Line1d_System_Cuspy_Laplace_RandomForcing.py
        python Line2d_Cuspy_Laplace.py
